# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := hge_static
DEFS_Default :=

# Flags passed to all source files.
CFLAGS_Default :=

# Flags passed to only C files.
CFLAGS_C_Default :=

# Flags passed to only C++ files.
CFLAGS_CC_Default :=

INCS_Default := \
	-Iinclude \
	-Isrc/core

OBJS := \
	$(obj).target/$(TARGET)/src/core/graphics.o \
	$(obj).target/$(TARGET)/src/core/ini.o \
	$(obj).target/$(TARGET)/src/core/input.o \
	$(obj).target/$(TARGET)/src/core/random.o \
	$(obj).target/$(TARGET)/src/core/resource.o \
	$(obj).target/$(TARGET)/src/core/sound.o \
	$(obj).target/$(TARGET)/src/core/system.o \
	$(obj).target/$(TARGET)/src/core/timer.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default :=

LIBS :=

$(obj).target/libhge_static.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/libhge_static.a: LIBS := $(LIBS)
$(obj).target/libhge_static.a: TOOLSET := $(TOOLSET)
$(obj).target/libhge_static.a: $(OBJS)
	$(call create_thin_archive,$@,$^)

# Add target alias
.PHONY: hge_static
hge_static: $(obj).target/libhge_static.a

# Add target alias to "all" target.
.PHONY: all
all: hge_static

