# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := test_app
DEFS_Default :=

# Flags passed to all source files.
CFLAGS_Default :=

# Flags passed to only C files.
CFLAGS_C_Default :=

# Flags passed to only C++ files.
CFLAGS_CC_Default :=

INCS_Default := \
	-Iinclude

OBJS := \
	$(obj).target/$(TARGET)/test_main.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/libhge_static.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default :=

LIBS :=

$(builddir)/test_app: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/test_app: LIBS := $(LIBS)
$(builddir)/test_app: LD_INPUTS := $(OBJS) $(obj).target/libhge_static.a
$(builddir)/test_app: TOOLSET := $(TOOLSET)
$(builddir)/test_app: $(OBJS) $(obj).target/libhge_static.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/test_app
# Add target alias
.PHONY: test_app
test_app: $(builddir)/test_app

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/test_app

